# Generated by Django 3.2.9 on 2022-05-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_commemt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commemt',
            new_name='Comment',
        ),
    ]
